namespace NodeJS {
  interface ProcessEnv extends NodeJS.ProcessEnv {
    IDENTITYSERVERPROVIDER_ID: string
    IDENTITYSERVERPROVIDER_SCOPE: string
    IDENTITYSERVERPROVIDER_NAME: string
    IDENTITYSERVERPROVIDER_CLIENTID: string
    IDENTITYSERVERPROVIDER_CLIENTSECRET: string
    IDENTITYSERVERPROVIDER_ISSUER: string
    SECRET: string
  }
}
